<?php
/**
 * Wave 4 — Performance optimizations (JS defer, jQuery migrate removal,
 * emoji + low-value head cleanup).
 *
 * Companion to inc/critical-css.php (CSS deferral) and inc/enqueue.php
 * (font preload + GSAP SRI). All filters guard `is_admin()` so wp-admin
 * keeps full default behaviour.
 *
 * @package Saltelli
 * @since 1.3.0 Wave 4
 */
defined('ABSPATH') || exit;

/* ------------------------------------------------------------------ */
/* 1. Defer jQuery + jquery-migrate + honeypot wpa.js                  */
/* ------------------------------------------------------------------ */
/* Pre-Wave 4 the WP-core jQuery + jquery-migrate were render-blocking
 * in <head> (~108 KB unused JS per Lighthouse). Honeypot's wpa.js is
 * also enqueued in <head> via plugin default. All three are deferred so
 * they execute at DOMContentLoaded (after parsing) instead of blocking
 * first paint.
 *
 * Safety:
 * - No theme code uses jQuery (verified: zero $(...) or jQuery(...) in
 *   wp-content/themes/saltelli/).
 * - The wpascript-js-after inline localize block only declares a global
 *   `wpa_field_info` object — no jQuery calls.
 * - Defer preserves DOM order, so jquery → jquery-migrate → wpa.js still
 *   execute in correct dependency order.
 */
add_filter('script_loader_tag', 'saltelli_defer_legacy_scripts', 11, 2);
function saltelli_defer_legacy_scripts($tag, $handle) {
    if (is_admin()) {
        return $tag;
    }
    static $defer_handles = [
        'jquery',
        'jquery-core',
        'jquery-migrate',
        'wpascript', // honeypot plugin
    ];
    if (!in_array($handle, $defer_handles, true)) {
        return $tag;
    }
    if (strpos($tag, ' defer') !== false) {
        return $tag;
    }
    return str_replace(' src=', ' defer src=', $tag);
}

/* ------------------------------------------------------------------ */
/* 2. Remove jquery-migrate dependency from jquery                     */
/* ------------------------------------------------------------------ */
/* jquery-migrate (~10 KB) only matters for very old plugin code that
 * still uses removed jQuery 1.x APIs. Saltelli theme + active plugins
 * (ACF, Redirection, honeypot, Yoast) are all jQuery 3.x clean. */
add_action('wp_default_scripts', 'saltelli_remove_jquery_migrate');
function saltelli_remove_jquery_migrate(&$scripts) {
    if (is_admin()) {
        return;
    }
    if (!isset($scripts->registered['jquery'])) {
        return;
    }
    $jquery = $scripts->registered['jquery'];
    if (!empty($jquery->deps)) {
        $jquery->deps = array_values(array_diff($jquery->deps, ['jquery-migrate']));
    }
}

/* ------------------------------------------------------------------ */
/* 3. Remove WP emoji detection + styles                               */
/* ------------------------------------------------------------------ */
/* wp-emoji-release.min.js (~14 KB), wp-emoji-settings inline JSON, and
 * the inline emoji <style> block are all unused: site copy is Italian,
 * emojis are not part of the brand. */
add_action('init', 'saltelli_disable_emoji');
function saltelli_disable_emoji() {
    remove_action('wp_head', 'print_emoji_detection_script', 7);
    remove_action('admin_print_scripts', 'print_emoji_detection_script');
    remove_action('wp_print_styles', 'print_emoji_styles');
    remove_action('admin_print_styles', 'print_emoji_styles');
    remove_filter('the_content_feed', 'wp_staticize_emoji');
    remove_filter('comment_text_rss', 'wp_staticize_emoji');
    remove_filter('wp_mail', 'wp_staticize_emoji_for_email');

    // Remove emoji from TinyMCE plugin list (defensive, ACF/Yoast safe)
    add_filter('tiny_mce_plugins', function ($plugins) {
        return is_array($plugins) ? array_values(array_diff($plugins, ['wpemoji'])) : [];
    });

    // Stop browsers from looking up s.w.org for emoji svg
    add_filter('emoji_svg_url', '__return_false');
}

/* ------------------------------------------------------------------ */
/* 4. Disable XML-RPC (security + perf)                                */
/* ------------------------------------------------------------------ */
add_filter('xmlrpc_enabled', '__return_false');
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wlwmanifest_link');

/* ------------------------------------------------------------------ */
/* 5. Remove WP generator meta + RSS generator                         */
/* ------------------------------------------------------------------ */
remove_action('wp_head', 'wp_generator');
add_filter('the_generator', '__return_empty_string');

/* ------------------------------------------------------------------ */
/* 6. Wave 4.5 — Serve WebP via <picture> element with fallback        */
/* ------------------------------------------------------------------ */
/* Wraps `wp_get_attachment_image` output in <picture><source webp><img>.
 * WebP files are stored with append pattern (image.jpg.webp) — convention
 * matches existing 1325 webp generated by previous bulk pass. The filter
 * is opt-in: if no .webp sibling exists, returns the original markup
 * unchanged, so legacy uploads still work.
 *
 * Browser support: <picture> + <source type="image/webp"> is supported
 * everywhere except IE11. Modern browsers pick the WebP when available.
 *
 * Lighthouse impact: blog-archive page (12 featured images) is most
 * affected — bytes-transferred reduction ~70-80% per image.
 */
add_filter('wp_get_attachment_image', 'saltelli_serve_webp_picture', 10, 5);
function saltelli_serve_webp_picture($html, $attachment_id, $size, $icon, $attr) {
    if (is_admin() || is_feed() || empty($html)) {
        return $html;
    }

    // Skip if already wrapped (idempotent — defensive)
    if (strpos($html, '<picture') !== false) {
        return $html;
    }

    $src_full = wp_get_attachment_image_url($attachment_id, $size);
    if (!$src_full) {
        return $html;
    }

    // Append pattern: image.jpg → image.jpg.webp
    $webp_url = $src_full . '.webp';
    $webp_path = str_replace(content_url(), WP_CONTENT_DIR, $webp_url);

    if (!file_exists($webp_path)) {
        return $html;
    }

    return '<picture>'
         . '<source srcset="' . esc_url($webp_url) . '" type="image/webp">'
         . $html
         . '</picture>';
}

/**
 * Wave 4.5 — Build inline `style="background-image: ..."` with WebP fallback.
 *
 * Returns a dual background-image declaration for robust browser support:
 *   1. background-image: url('source.jpg')                                              — fallback
 *   2. background-image: image-set(url('source.jpg.webp') type('image/webp'), url('source.jpg'))
 *      — modern browsers (Chrome 90+, Firefox 89+, Safari 14+) pick WebP automatically.
 *
 * Cache-safe (no Vary: Accept needed): the URL itself contains both formats,
 * the browser picks based on its own capability — same response for all UAs.
 *
 * Usage in templates:
 *   <div style="<?= saltelli_bg_with_webp($url) ?>">
 *
 * If WebP sibling missing → returns plain `background-image:url(...)` only.
 *
 * @param string $url Original image URL.
 * @return string Inline-CSS string (no enclosing `style="..."`).
 */
if (!function_exists('saltelli_bg_with_webp')) :
function saltelli_bg_with_webp($url) {
    if (empty($url)) {
        return '';
    }

    $webp_url = $url . '.webp';
    $webp_path = str_replace(content_url(), WP_CONTENT_DIR, $webp_url);

    if (!file_exists($webp_path)) {
        return 'background-image:url(' . esc_url($url) . ')';
    }

    // NOTE: single-quotes intorno alle URL nel CSS function arg — sono dentro
    // a uno style="..." double-quoted, quindi il quoting interno DEVE essere
    // single. esc_url() URL-encoda i single-quote, quindi è safe.
    return 'background-image:url(' . esc_url($url) . ');'
         . "background-image:image-set(url('" . esc_url($webp_url) . "') type('image/webp'),url('" . esc_url($url) . "'))";
}
endif;
